### ISSUE TITLE
Crashes on exiting (double free?)

### ISSUE THREAD

**Issue by xinyazhang** [tycheng/PlanetRenderer#10]
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib          0x00007fff8c2f8286 __pthread_kill + 10
1   libsystem_c.dylib               0x00007fff87ff4b53 abort + 129
2   libsystem_malloc.dylib          0x00007fff93359937 free + 428
3   org.qt-project.QtGui            0x0000000108c8a710 QOpenGLFunctions_3_3_Core::~QOpenGLFunctions_3_3_Core() + 96
4   PlanetRenderer                  0x000000010714f44a SceneObject::~SceneObject() + 778 (SceneObject.cc:40)
5   PlanetRenderer                  0x0000000107158b61 TextureSkyDome::~TextureSkyDome() + 241 (TextureSkyDome.cc:39)
6   PlanetRenderer                  0x0000000107158b85 TextureSkyDome::~TextureSkyDome() + 21 (TextureSkyDome.cc:39)
7   PlanetRenderer                  0x0000000107158ba9 TextureSkyDome::~TextureSkyDome() + 25 (TextureSkyDome.cc:37)
8   PlanetRenderer                  0x000000010713bd01 RenderThread::~RenderThread() + 689 (memory:2625)
9   PlanetRenderer                  0x000000010713c9a5 RenderThread::~RenderThread() + 21 (RenderThread.cc:25)
10  PlanetRenderer                  0x000000010713c9c9 RenderThread::~RenderThread() + 25 (RenderThread.cc:23)
11  PlanetRenderer                  0x0000000107139dda nexus::terminate() + 426 (nexus.cc:25)
12  PlanetRenderer                  0x00000001071364e8 main + 392 (main.cc:29)
13  libdyld.dylib                   0x00007fff8b5885c9 start + 1

**Comment by xinyazhang** [comment]
Ok I think I have a theory. We should not create multiple QOpenGLFunctions_3_3_Core objects in a single thread.

If verified, mark this a dup of #11

**Comment by xinyazhang** [comment]
Also crashes on Linux, at the same point.

#0  0x0000003f5a6348d7 in raise () at /lib64/libc.so.6
#1  0x0000003f5a63653a in abort () at /lib64/libc.so.6
#2  0x0000003f5a677da3 in  () at /lib64/libc.so.6
#3  0x0000003f5a6839f5 in free () at /lib64/libc.so.6
#4  0x0000003f1964c4b5 in QOpenGLFunctions_3_3_Core::~QOpenGLFunctions_3_3_Core() () at /lib64/libQt5Gui.so.5
#5  0x00000000004307da in SceneObject::~SceneObject() (this=0x7fffd807ab00, __in_chrg=<optimized out>)
    at /home/zxy/courses/cg/PlanetRenderer/src/scene/SceneObject.cc:38
#6  0x000000000042d154 in TextureSkyDome::~TextureSkyDome() (this=0x7fffd807ab00, __in_chrg=<optimized out>)
    at /home/zxy/courses/cg/PlanetRenderer/src/scene/TextureSkyDome.cc:37
#7  0x000000000042d184 in TextureSkyDome::~TextureSkyDome() (this=0x7fffd807ab00, __in_chrg=<optimized out>)
    at /home/zxy/courses/cg/PlanetRenderer/src/scene/TextureSkyDome.cc:39
#8  0x00000000004265ba in std::default_delete<TextureSkyDome>::operator()(TextureSkyDome_) const (this=0x80d798, __ptr=0x7fffd807ab00)
    at /usr/include/c++/4.9.2/bits/unique_ptr.h:76
#9  0x0000000000425d25 in std::unique_ptr<TextureSkyDome, std::default_delete<TextureSkyDome> >::~unique_ptr() (this=0x80d798, __in_chrg=<optimized out>) at /usr/include/c++/4.9.2/bits/unique_ptr.h:236
#10 0x0000000000424bd2 in RenderThread::~RenderThread() (this=0x80d750, __in_chrg=<optimized out>)
    at /home/zxy/courses/cg/PlanetRenderer/src/utils/RenderThread.cc:22
#11 0x0000000000424c62 in RenderThread::~RenderThread() (this=0x80d750, __in_chrg=<optimized out>)
    at /home/zxy/courses/cg/PlanetRenderer/src/utils/RenderThread.cc:25
#12 0x0000000000423415 in nexus::terminate() () at /home/zxy/courses/cg/PlanetRenderer/src/utils/nexus.cc:24
#13 0x0000000000421216 in main(int, char_*) (argc=1, argv=0x7fffffffdf68) at /home/zxy/courses/cg/PlanetRenderer/src/main.cc:29

**Comment by xinyazhang** [comment]
Duplicate of issue #11
